[package]
name = "nessie"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.9.4"
bytesize = "2.1.0"
clap = { version = "4.5.48", features = ["derive"] }
eframe = "0.33.0"
egui = "0.33.0"
egui_extras = "0.33.0"
env_logger = "0.11.8"
log = "0.4.28"
modular-bitfield = "0.13.0"
phf = { version = "0.13.1", features = ["macros"] }
rand = "0.9.2"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
