[package]
name = "nessie"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = {version = "1.0.100", default-features = false}
argh = "0.1.13"
bitflags = "2.10.0"
bytesize = "2.2.0"
compile-time = "0.2.0"
cpal = { version = "0.16.0", features = ["wasm-bindgen"] }
eframe = { version = "0.33.2", default-features = false, features = [
  "default_fonts",
  "glow",
  "wayland",
  "x11"
] }
egui = "0.33.2"
egui_extras = { version = "0.33.2", features = ["image"] }
log = "0.4.28"
modular-bitfield = "0.13.0"
phf = { version = "0.13.1", default-features = false, features = ["macros"] }
rfd = "0.15.4"
ringbuf = "0.4.8"
image = { version = "0.25.9", default-features = false, features = ["png"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11.8"
puffin = "0.19.1"
puffin_http = "0.16.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
wasm-bindgen-futures = "0.4.55"
web-sys = "0.3.82"
web-time = "1.1.0"

[profile.release]
lto = true
codegen-units = 1
