[package]
name = "nessie"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = "0.1.13"
bitflags = "2.10.0"
bytesize = "2.2.0"
eframe = { version = "0.33.0", default-features = false, features = [
  "default_fonts",
  "glow",
  "wayland",
  "x11"
] }
egui = "0.33.0"
egui_extras = { version = "0.33.0", features = ["image"] }
image = { version = "0.25.8", default-features = false, features = ["png"] }
log = "0.4.28"
modular-bitfield = "0.13.0"
phf = { version = "0.13.1", features = ["macros"] }
rfd = "0.15.4"
wasm-bindgen-futures = "0.4.55"
web-sys = "0.3.82"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
puffin = "0.19.1"
puffin_http = "0.16.1"
env_logger = "0.11.8"

[profile.release]
lto = true
codegen-units = 1
