[package]
name = "nessie"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = "0.1.13"
bitflags = "2.10.0"
bytesize = "2.2.0"
eframe = "0.33.0"
egui = "0.33.0"
egui_extras = { version = "0.33.0", features = ["image"] }
env_logger = "0.11.8"
image = { version = "0.25.8", default-features = false, features = ["png"] }
log = "0.4.28"
modular-bitfield = "0.13.0"
phf = { version = "0.13.1", features = ["macros"] }
puffin = "0.19.1"
puffin_http = "0.16.1"
rfd = "0.15.4"

[profile.release]
lto = true
codegen-units = 1
