[package]
name = "nessie"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.9.4"
bytesize = "2.1.0"
clap = { version = "4.5.47", features = ["derive"] }
eframe = "0.32.3"
egui = "0.32.3"
env_logger = "0.11.8"
log = "0.4.28"
modular-bitfield = "0.12.0"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
